---
- name: Install Pre-Reqs
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install Python3
      ansible.builtin.package:
        name: python3
        state: present

- name: Install and Manage MySQL 8.0 AlmaLinux 8
  hosts: localhost
  become: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - password: Password1
  tasks:
    - name: install python mysql connector
      become: true
      ansible.builtin.package:
        name:
          - python3-pymysql
          - mysql-server
          - mysql-client
        state: present

    - name: Manage Mysqld service RedHat
      become: true
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
      when: ansible["os_family'] == "RedHat"

    - name: Manage Mysqld service Debian
      become: true
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
      when: ansible["os_family'] == "Debian"

    - name: Manage Mysql Root
      become: true
      mysql_user:
        login_user: root
        login_password: "{{ password }}"
        name: root
        password: "{{ password }}"
        check_implicit_admin: true
    - name: Import Database
      mysql_db:
        login_user: root
        login_password: "{{ password }}"
        name: all
        state: import
        target: "{{ lookup('env', 'HOME') }}/mysql8/northwindmysql.sql"

    - name: user mysql
      mysql_user:
        name: tux
        host: localhost
        password: "{{ password }}"
        login_user: root
        login_password: "{{ password }}"
        priv: "northwind.*:SELECT"
        update_password: on_create